# Generated by Django 2.1.5 on 2019-02-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(max_length=40),
        ),
    ]
